### ISSUE TITLE
Hibernate 쿼리 콘솔 출력 설정

### ISSUE THREAD

**Issue by J-I-H-O** [woowacourse-teams/2024-friendogly#109]
## 요구 사항
- JPA를 통해 실행되는 쿼리가 콘솔에 출력되도록 옵션 수정

**application.yml**
```yml
spring:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  application:
    name: friendogly
  sql:
    init:
      encoding: utf-8

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

```
