### ISSUE TITLE
이미지 업로드 용량 제한을 5MB로 높인다.

### ISSUE THREAD

**Issue by takoyakimchi** [woowacourse-teams/2024-friendogly#641]
## 요구 사항
- 현재는 이미지 업로드 시 용량을 1MB로 제한하고 있다.
- 원인은 다음과 같이 두 가지다.
  - nginx의 기본 설정: request의 최대 크기를 1MB로 제한
  - Spring의 기본 설정은: 하나의 파일에 대해 최대 용량을 1MB로 제한
- nginx와 `application.yml`에서 설정을 변경하여 용량 제한을 높인다.

## 설정 예시
```nginx
# nginx.conf
http {
  client_max_body_size 5M;
  # ...
```

```yaml
# application.yml
spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
```
